### PR TITLE
affinity: always define affinity if not found

### PR DESCRIPTION
**Pull request by aconchillo**

### CODE REVIEW

**Comment by aconchillo** [comment]
@gdt This should fix the NetBSD issue. It will throw a couple of warnings though, but it should be OK.

The problem is that in configure.ac we considered all non-darwin platforms `generic` and getaffinity/setaffinity were not implemented in the generic file.

I just simplified and removed files and everything is now in `affinity.scm`. If those procedures are defined we are good, otherwise we just returned no-ops.

**Comment by aconchillo** [comment]
> @gdt This should fix the NetBSD issue. It will throw a couple of warnings though, but it should be OK.
> 
> The problem is that in configure.ac we considered all non-darwin platforms `generic` and getaffinity/setaffinity were not implemented in the generic file.
> 
> I just simplified and removed files and everything is now in `affinity.scm`. If those procedures are defined we are good, otherwise we just returned no-ops.

This will work for any platforms now.

**Comment by gdt** [comment]
1.2.0 with this patch builds and passes most tests, so this is a vast improvement.  It's still running the race-until test:
```
assert run-fibers on (let lp ((n 0)) (when (< n 100000000) (lp (#{1+}# n)))) terminates: ok (0.223087867 s)
assert run-fibers on (race-until 100) terminates: 

and ps shows
29575 gdt       25    0   192M   45M CPU/3     14:33 98.88% 98.88% guile
```

I'll leave it  for a while, but this seems likely stuck.

**Comment by gdt** [comment]
After 20 minutes of CPU  time I killed the process, but the other tests all passed.

**Comment by aconchillo** [comment]
> After 20 minutes of CPU time I killed the process, but the other tests all passed.

I think I've seen that sometimes with libevent. Does it reproduce every time?

**Comment by gdt** [comment]
I will retest.  I wonder if the test should have a counter and fail if it gets too high.

**Comment by emixa-d** [comment]
New code  looks fine to me.

**Review by emixa-d — APPROVED** [review]

**Comment by aconchillo** [comment]
> I will retest. I wonder if the test should have a counter and fail if it gets too high.

This might indicate an issue in the test itself or in fibers. I'll try to find some time to reproduce and investigate. Let me know if it always reproduces or if it's a random thing.

**Pull request merged**
